name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches: -main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run tests
        run: npm run test:backend:unit
